name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        default: "dev"
        description: "Ambiente"

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Code
        uses: actions/checkout@v3
        with:
          # repository: snapfi/paulo-test
          repository: snapfi/k8s
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy 
        id: Deploy 
        uses: snapfi/update-image-tag-action@main
