name: Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Code
        uses: actions/checkout@v3
        with:
          repository: snapfi/paulo-test
          token: ${{ secrets.ACCESS_TOKEN }}

  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        id: selftest
        uses: snapfi/update-image-tag-action@main
        with:
          environment: dev

  approval:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Manual Approval
      id: approval
      run: |
        # Use o comando `read` para aguardar uma aprovação manual
        echo "Please approve the deployment to production"
        echo "::set-output name=approved::true"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Check Approval Status
        id: check-approval
        run: echo "Approval status is ${{ needs.manual-approval.outputs.approved }}"
          
      - name: Deploy to Prod
        id: selftest
        uses: snapfi/update-image-tag-action@main
        with:
          environment: prod
