name: Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Code
        uses: actions/checkout@v3
        with:
          repository: snapfi/paulo-test
          token: ${{ secrets.ACCESS_TOKEN }}

  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev
        id: selftest
        uses: snapfi/update-image-tag-action@main
        with:
          environment: dev

  approval:
    if: success() && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Approval
      id: approval
      run: echo "Please approve the deployment to production"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Deploy to Prod
        id: selftest
        uses: snapfi/update-image-tag-action@main
        with:
          environment: prod
